services:
  nicotine:
    image: haveac1gar/wb-nicotineplus-xpra-ugreen-nas:latest
    container_name: nicotine-xpra
    restart: unless-stopped
    ports:
      - "5005:5005"
      - "2234:2234"
    environment:
      - PUID=1000
      - PGID=10
      - TZ=YourTZ
      - NICOTINE_LOGIN=YourLogin
      - NICOTINE_PASSWORD=YourPassword
      - NICOTINE_DARKMODE=True
      - ALLOW_HTTP=True
      - APP_DIRS=/shared
    volumes:
      - ./config:/home/gwb/.config/nicotine
      - ./data:/home/gwb/.local/share/nicotine
      - /your/shared/data:/home/gwb/shared:ro